### ISSUE TITLE
Relative paths in Cobertura reports are treated relative to the current directory instead of the projectBaseDir

### ISSUE THREAD

**Issue by abbeyj** [wenns/sonar-cxx#426]
When using reports in Cobertura format that contain relative paths and running sonar-runner from a directory other than the projectBaseDir, the paths are canonicalized incorrectly.  This leads to the relevant files not being found.

For instance, say my project base directory is ./base_dir and I also have ./sonar/sonar-project.properties.  After building the project, I switch to the ./sonar directory and then run sonar-runner.  The current directory while running is ./sonar but relative paths in the Cobertura report should be taken relative to the projectBaseDir.  Making them relative to the current directory isn't going to find anything as the only thing in the sonar directory is the sonar-project.properties file.

I have sample project to demonstrate this at http://files.stardrifter.org/pub/cobertura_paths.tar.gz

To use it:
$ tar xzvf cobertura_paths.tar.gz
$ cd cobertura_paths/base_dir
$ make
$ cd ../sonar
$ sonar-runner

You'll see a message like
WARN  - Cannot find the file '&lt;snip&gt;/cobertura_paths/**sonar**/main.cpp', ignoring coverage measures

It should be looking instead for .../cobertura_paths/**base_dir**/main.cpp which is where the file is actually located.

I believe the problem occurs at the normalizePath call here:
https://github.com/wenns/sonar-cxx/blob/79894beea01bd829275c8c6e5502855bcf063cb1/sonar-cxx-plugin/src/main/java/org/sonar/plugins/cxx/coverage/CoberturaParser.java#L70

This needs to be modified to take into account the projectBaseDir from the .properties file and not just use the current directory as CxxUtils.normalizePath does.

**Comment by guwirth** [comment]
Maybe wiki helps https://github.com/wenns/sonar-cxx/wiki/Path-and-path-separator-issues

**Comment by abbeyj** [comment]
That link doesn't help me.  I'm going by the instructions at 
http://docs.sonarqube.org/display/SONAR/Analyzing+with+SonarQube+Runner#AnalyzingwithSonarQubeRunner-AdvancedUsage
and
http://docs.sonarqube.org/display/SONAR/Analysis+Parameters#AnalysisParameters-projectBaseDir

This says that I should be able to set projectBaseDir to a different directory than where I started sonar-runner (where the sonar-project.properties file is located).  The effect of that is that all relative paths should be treated as if they were relative to projectBaseDir.  Or, in other words, it should be as if I started sonar-runner from that directory.  This works for most cases (relative paths specified in the sonar-project.properites file, for instance) but it fails with relative paths in Cobertura reports.

**Comment by wenns** [comment]
Thanks for reporting this, it looks like a plain bug to me. We'll fix that.

**Comment by jmecosta** [comment]
#358 might cover this? Not completely sure

**Comment by guwirth** [comment]
CxxUtils.normalizePath: maybe one of this can used instead: http://grepcode.com/file/repo1.maven.org/maven2/org.codehaus.sonar/sonar-plugin-api/4.2/org/sonar/api/utils/PathUtils.java?av=f (does not solve the projectBaseDir problem).

**Comment by guwirth** [comment]
Maybe fixed with #358. Please try.

**Comment by guwirth** [comment]
@abbeyj could you please test with v0.9.3-RC1?

**Comment by jmecosta** [comment]
@guwirth close -> release -> re-open if problem persists.

**Comment by abbeyj** [comment]
I've tested this with both 0.9.3 and 0.9.4-RC3 and it still occurs with both of them.  Please re-open this.
